#spring.application.name=ticket-api

spring:
  application:
    name: ticket-api

server:
  port: 0
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true